### ISSUE TITLE
unknown type name 'pthread_mutex_t'

### ISSUE THREAD

**Issue by ryandesign** [kisli/vmime#60]
Building libvmime 0.9.1 fails on OS X 10.9 Mavericks:

```
/bin/sh ../libtool  --tag=CXX   --mode=compile /usr/bin/clang++ -DHAVE_CONFIG_H -I. -I.. -I/opt/local/include -I..  -D_REENTRANT=1 -D_THREAD_SAFE=1 -I/opt/local/include -I/opt/local/include/p11-kit-1 -I/opt/local/include -fno-common -DPIC -ansi -pedantic -W -Wall -Wpointer-arith -Wold-style-cast -Wconversion    -isystem/opt/local/include  -O2 -c -o utility_smartPtrInt.lo utility_smartPtrInt.cpp
libtool: compile:  /usr/bin/clang++ -DHAVE_CONFIG_H -I. -I.. -I/opt/local/include -I.. -D_REENTRANT=1 -D_THREAD_SAFE=1 -I/opt/local/include -I/opt/local/include/p11-kit-1 -I/opt/local/include -fno-common -DPIC -ansi -pedantic -W -Wall -Wpointer-arith -Wold-style-cast -Wconversion -isystem/opt/local/include -O2 -c utility_smartPtrInt.cpp  -fno-common -DPIC -o .libs/utility_smartPtrInt.o
In file included from utility_smartPtrInt.cpp:24:
../vmime/utility/smartPtrInt.hpp:59:2: error: unknown type name 'pthread_mutex_t'
        pthread_mutex_t m_mutex;
        ^
utility_smartPtrInt.cpp:41:9: error: cannot initialize return object of type 'vmime::utility::refManager *' with an rvalue of type 'vmime::utility::refManagerImpl *'
        return new refManagerImpl(obj);
               ^~~~~~~~~~~~~~~~~~~~~~~
utility_smartPtrInt.cpp:110:3: error: cannot initialize object parameter of type 'vmime::utility::refManager' with an expression of type 'vmime::utility::refManagerImpl'
                deleteObjectImpl(m_object);
                ^~~~~~~~~~~~~~~~
In file included from utility_smartPtrInt.cpp:24:
In file included from ../vmime/utility/smartPtrInt.hpp:29:
../vmime/utility/smartPtr.hpp:131:6: warning: private field 'foo' is not used [-Wunused-private-field]
        int foo;
            ^
In file included from utility_smartPtrInt.cpp:24:
../vmime/utility/smartPtrInt.hpp:59:18: warning: private field 'm_mutex' is not used [-Wunused-private-field]
        pthread_mutex_t m_mutex;
                        ^
2 warnings and 3 errors generated.
```

This was also [reported to the MacPorts project](https://trac.macports.org/ticket/41292); you can find the full log attached to that ticket.

**Comment by Serge3leo** [comment]
Last trunk commit 9df44078b87785f114689fc0b12e084aba903df0 of 8 may 2015 successfully builds on OS X 10.10 Yosemite

**Comment by vincent-richard** [comment]
Thank you for your feedback!
