### ISSUE TITLE
Can't compile with Clang 3.5

### ISSUE THREAD

**Issue by abyss7** [kisli/vmime#92]
Gives an error:

In file included from /usr/include/vmime/vmime.hpp:32:
/usr/include/vmime/base.hpp:255:12: error: use 'template' keyword to treat 'dynamicCast' as a dependent template name
                return y.dynamicCast <X>();
                         ^
1 error generated.
